function Fout = velocities_sphere( q, dq , ~, data)

% 3 constraint equations of the model
R = data.R;

r1 = q(1);
r2 = q(2);
r3 = q(3);
r4 = q(4);
alpha = q(5);
beta = q(6);
gamma = q(7);


dr1 =dq(1);
dr2 =dq(2);
dr3 =dq(3);
dr4 =dq(4);
omx = dq(5);
omy = dq(6);
omz = dq(7);

sqrt2 = sqrt(2);
sqrt6 = sqrt(6);


Fout = zeros(3,4);

Fout(:,1) = [omy*R + omy*r1*cos(beta)*cos(gamma) - omz*r1*cos(gamma)*sin(alpha)*sin(beta) + dr1*sin(alpha)*sin(gamma) + cos(alpha)*(dr1*cos(gamma)*sin(beta) + omz*r1*sin(gamma)),...
   -(omx*R) - omx*r1*cos(beta)*cos(gamma) + dr1*cos(gamma)*sin(alpha)*sin(beta) + omz*r1*sin(alpha)*sin(gamma) + cos(alpha)*(omz*r1*cos(gamma)*sin(beta) - dr1*sin(gamma)), ...
   dr1*cos(beta)*cos(gamma) - r1*(cos(alpha)*(omy*cos(gamma)*sin(beta) + omx*sin(gamma)) + sin(alpha)*(-(omx*cos(gamma)*sin(beta)) + omy*sin(gamma)))]';

Fout(:,2) = [(3*omy*R - r2*cos(beta)*(omy*cos(gamma) + 2*omz*sqrt2*sin(alpha)) - 2*omy*r2*sqrt2*sin(beta) + omz*r2*cos(gamma)*sin(alpha)*sin(beta) - dr2*sin(alpha)*sin(gamma) + ...
      cos(alpha)*(2*dr2*sqrt2*cos(beta) - dr2*cos(gamma)*sin(beta) - omz*r2*sin(gamma)))/3.,...
   (-3*omx*R + cos(beta)*(omx*r2*cos(gamma) + 2*dr2*sqrt2*sin(alpha)) + 2*omx*r2*sqrt2*sin(beta) - dr2*cos(gamma)*sin(alpha)*sin(beta) - omz*r2*sin(alpha)*sin(gamma) + ...
      cos(alpha)*(2*omz*r2*sqrt2*cos(beta) - omz*r2*cos(gamma)*sin(beta) + dr2*sin(gamma)))/3.,...
   (cos(beta)*(-(dr2*cos(gamma)) + 2*omx*r2*sqrt2*sin(alpha)) - 2*dr2*sqrt2*sin(beta) - omx*r2*cos(gamma)*sin(alpha)*sin(beta) + omy*r2*sin(alpha)*sin(gamma) + ...
      r2*cos(alpha)*(-2*omy*sqrt2*cos(beta) + omy*cos(gamma)*sin(beta) + omx*sin(gamma)))/3.]';

Fout(:,3) = [(3*omy*R - dr3*sqrt6*cos(gamma)*sin(alpha) + omy*r3*sqrt2*sin(beta) + omz*r3*cos(gamma)*sin(alpha)*sin(beta) - dr3*sin(alpha)*sin(gamma) - omz*r3*sqrt6*sin(alpha)*sin(beta)*sin(gamma) + ...
      r3*cos(beta)*(-(omy*cos(gamma)) + omz*sqrt2*sin(alpha) + omy*sqrt6*sin(gamma)) - ...
      cos(alpha)*(dr3*sqrt2*cos(beta) + omz*r3*sqrt6*cos(gamma) + dr3*cos(gamma)*sin(beta) + omz*r3*sin(gamma) - dr3*sqrt6*sin(beta)*sin(gamma)))/3.,...
   (-3*omx*R - omz*r3*sqrt6*cos(gamma)*sin(alpha) - omx*r3*sqrt2*sin(beta) - dr3*cos(gamma)*sin(alpha)*sin(beta) - omz*r3*sin(alpha)*sin(gamma) + dr3*sqrt6*sin(alpha)*sin(beta)*sin(gamma) - ...
      cos(beta)*(-(omx*r3*cos(gamma)) + dr3*sqrt2*sin(alpha) + omx*r3*sqrt6*sin(gamma)) + ...
      cos(alpha)*(-(omz*r3*sqrt2*cos(beta)) + cos(gamma)*(dr3*sqrt6 - omz*r3*sin(beta)) + (dr3 + omz*r3*sqrt6*sin(beta))*sin(gamma)))/3.,...
   (omy*r3*sqrt6*cos(gamma)*sin(alpha) + dr3*sqrt2*sin(beta) - omx*r3*cos(gamma)*sin(alpha)*sin(beta) + omy*r3*sin(alpha)*sin(gamma) + omx*r3*sqrt6*sin(alpha)*sin(beta)*sin(gamma) + ...
      cos(beta)*(-(dr3*cos(gamma)) - omx*r3*sqrt2*sin(alpha) + dr3*sqrt6*sin(gamma)) + ...
      r3*cos(alpha)*(omy*sqrt2*cos(beta) + cos(gamma)*(omx*sqrt6 + omy*sin(beta)) + (omx - omy*sqrt6*sin(beta))*sin(gamma)))/3.]';

Fout(:,4) = [(3*omy*R + dr4*sqrt6*cos(gamma)*sin(alpha) + omy*r4*sqrt2*sin(beta) + omz*r4*cos(gamma)*sin(alpha)*sin(beta) - dr4*sin(alpha)*sin(gamma) + omz*r4*sqrt6*sin(alpha)*sin(beta)*sin(gamma) - ...
      r4*cos(beta)*(omy*cos(gamma) - omz*sqrt2*sin(alpha) + omy*sqrt6*sin(gamma)) - ...
      cos(alpha)*(dr4*sqrt2*cos(beta) - omz*r4*sqrt6*cos(gamma) + dr4*cos(gamma)*sin(beta) + omz*r4*sin(gamma) + dr4*sqrt6*sin(beta)*sin(gamma)))/3.,...
   (-3*omx*R + omz*r4*sqrt6*cos(gamma)*sin(alpha) - omx*r4*sqrt2*sin(beta) - dr4*cos(gamma)*sin(alpha)*sin(beta) - omz*r4*sin(alpha)*sin(gamma) - dr4*sqrt6*sin(alpha)*sin(beta)*sin(gamma) + ...
      cos(beta)*(omx*r4*cos(gamma) - dr4*sqrt2*sin(alpha) + omx*r4*sqrt6*sin(gamma)) - ...
      cos(alpha)*(omz*r4*sqrt2*cos(beta) + dr4*sqrt6*cos(gamma) + omz*r4*cos(gamma)*sin(beta) - dr4*sin(gamma) + omz*r4*sqrt6*sin(beta)*sin(gamma)))/3.,...
   (-(omy*r4*sqrt6*cos(gamma)*sin(alpha)) + dr4*sqrt2*sin(beta) - omx*r4*cos(gamma)*sin(alpha)*sin(beta) + omy*r4*sin(alpha)*sin(gamma) - omx*r4*sqrt6*sin(alpha)*sin(beta)*sin(gamma) - ...
      cos(beta)*(dr4*cos(gamma) + omx*r4*sqrt2*sin(alpha) + dr4*sqrt6*sin(gamma)) + ...
      r4*cos(alpha)*(omy*sqrt2*cos(beta) + cos(gamma)*(-(omx*sqrt6) + omy*sin(beta)) + (omx + omy*sqrt6*sin(beta))*sin(gamma)))/3.]';
